export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SHIPPING = "CART_SHIPPING"
export const CART_REMOVE_ADDRESS = "CART_REMOVE_ADDRESS"

export const PAYMENT_REQUEST = "PAYMENT_REQUEST"
export const PAYMENT_SUCCESSFUL = "PAYMENT_SUCCESSFUL"
export const PAYMENT_FAIL = "PAYMENT_FAIL"