export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_DETAIL_REQUEST  = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS"
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL"

export const USER_SIGNIN_REQUEST ="USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCESS ="USER_SIGNIN_SUCESS"
export const USER_SIGNIN_ERROR ="USER_SIGNIN_ERROR"
export const USER_SIGNOUT_REQUEST ="USER_SIGNOUT_REQUEST"

export const USER_REGISTER_REQUEST ="USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCESS ="USER_REGISTER_SUCESS"
export const USER_REGISTER_ERROR ="USER_REGISTER_ERROR"

